name: Monitor Competidores

on:
  schedule:
    - cron: '0 8 * * *'      # Todos los días a las 08:00 UTC
  workflow_dispatch:         # Permite dispararlo manualmente

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar monitor_competitors.py
        env:
          NEWSAPI_KEY:       ${{ secrets.NEWSAPI_KEY }}
          OPENAI_API_KEY:    ${{ secrets.OPENAI_API_KEY }}
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: python monitor.py

      - name: Commit state.json updates
        run: |
          git config user.name 'github-actions'
          git config user.email 'actions@github.com'
          git add state.json
          git commit -m 'chore: actualizar state.json tras monitor' || echo "No hay cambios en state.json"
          git push
