name: Monitor Competidores

permissions:
  contents: write

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt python-dotenv

      - name: Ejecutar monitor
        env:
          NEWSAPI_KEY:       ${{ secrets.NEWSAPI_KEY }}
          OPENAI_API_KEY:    ${{ secrets.OPENAI_API_KEY }}
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: python monitor.py

      - name: Commit state.json updates
        run: |
          git config user.name 'github-actions'
          git config user.email 'actions@github.com'
          git add state.json
          git commit -m 'chore: actualizar state.json tras monitor' || echo "No hay cambios en state.json"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: main
            force: true
