name: Monitor Competidores

# Necesario para que GITHUB_TOKEN pueda hacer git push
permissions:
  contents: write

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    # Aseguramos también a nivel de job
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true   # <- importante para dejar el GITHUB_TOKEN en .git/config

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt python-dotenv

      - name: Ejecutar monitor
        env:
          NEWSAPI_KEY:       ${{ secrets.NEWSAPI_KEY }}
          OPENAI_API_KEY:    ${{ secrets.OPENAI_API_KEY }}
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: python monitor.py

      - name: Commit state.json updates
        # GITHUB_TOKEN ya está disponible en el runner
        run: |
          git config user.name 'github-actions'
          git config user.email 'actions@github.com'
          git add state.json
          git commit -m 'chore: actualizar state.json tras monitor' || echo "No hay cambios"
          git push
